### ISSUE TITLE
I can't update PixelFed storage per user

### ISSUE THREAD

**Issue by colmaris** [pixelfed/support#152]
Hi all,

In first sorry for bad english it's not my main language.

I run Pixelfed with docker and a compose file take from this repo. At the installation i make a error to set `MAX_ACCOUNT_SIZE=`. I don't want the default 1gb limit, i want increase this limit to 5GB. But i have registred `5000` instead of `5000000`. Now users have a limit of 5mb instead of 5gb.

I modify my `.env` file, i have restart my containers and apply this command `php artisan config:cache` to cache the new configuration.
But in my profile account i seen always the limit to 5Mb. I see nothing in horizon.

Have you an idea ?

This is my compose file : 

```
pixelfed:
    image: colmaris/pixelfed:v0.11.3
    container_name: pixelfed
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.pixelfed-http.rule=Host(photo.${DOMAIN})
      - traefik.http.routers.pixelfed-http.entrypoints=http
      - traefik.http.routers.pixelfed-http.middlewares=https-redirect
      - traefik.http.routers.pixelfed-https.rule=Host(photo.${DOMAIN})
      - traefik.http.routers.pixelfed-https.entrypoints=https
      - traefik.http.routers.pixelfed-https.tls=true
      - traefik.http.routers.pixelfed-https.tls.certresolver=le
      - traefik.http.services.pixelfed.loadbalancer.server.port=80
    env_file: .env.pixelfed
    volumes:
      - /home/draconis/thrall/volumes/pixelfed/storage:/var/www/storage
      #- /home/draconis/thrall/volumes/pixelfed/bootstrap:/var/www/bootstrap/cache
      #- "./.env.pixelfed:/var/www/.env"
    networks:
      - web
      - interne
    depends_on:
      - pixelfed-db
      - pixelfed-redis    
  
pixelfed-worker:
    image: colmaris/pixelfed:v0.11.3
    container_name: pixelfed-worker
    restart: unless-stopped
    env_file: .env.pixelfed
    volumes:
      - /home/draconis/thrall/volumes/pixelfed/storage:/var/www/storage
      #- /home/draconis/thrall/volumes/pixelfed/bootstrap:/var/www/bootstrap/cache
    networks:
      - web
      - interne
    command: gosu www-data php artisan horizon
    depends_on:
      - pixelfed-db
      - pixelfed-redis
  
pixelfed-db:
    image: mariadb
    container_name: pixelfed-db
    restart: unless-stopped
    networks:
      - interne
    env_file: .env.pixelfed
    volumes:
      - /home/draconis/thrall/volumes/pixelfed/mariadb:/var/lib/mysql
 
pixelfed-redis:
    image: redis:5-alpine
    container_name: pixelfed-redis
    restart: unless-stopped
    env_file: .env.pixelfed
    sysctls:
      - net.core.somaxconn=4096
      #- vm.overcommit_memory=1
    volumes:
      - /home/draconis/thrall/volumes/pixelfed/redis:/data
    networks:
      - interne
```
      
This is my _**env**_ file : 

````## Crypto
APP_KEY=

## General Settings
APP_NAME="photo.draconis.me"
APP_ENV=production
APP_DEBUG=false
APP_URL=https://photo.draconis.me
APP_DOMAIN="photo.draconis.me"
ADMIN_DOMAIN="photo.draconis.me"
SESSION_DOMAIN="photo.draconis.me"

OPEN_REGISTRATION=true
ENFORCE_EMAIL_VERIFICATION=true
PF_MAX_USERS=10
OAUTH_ENABLED=true

APP_TIMEZONE=EUROPE/Paris
APP_LOCALE=fr

## Pixelfed Tweaks
LIMIT_ACCOUNT_SIZE=true
MAX_ACCOUNT_SIZE=5000000
MAX_PHOTO_SIZE=15000
MAX_AVATAR_SIZE=2000
MAX_CAPTION_LENGTH=500
MAX_BIO_LENGTH=125
MAX_NAME_LENGTH=30
MAX_ALBUM_LENGTH=10
IMAGE_QUALITY=80
PF_OPTIMIZE_IMAGES=true
PF_OPTIMIZE_VIDEOS=true
ADMIN_ENV_EDITOR=false
ACCOUNT_DELETION=true
ACCOUNT_DELETE_AFTER=false
MAX_LINKS_PER_POST=0
ENABLE_CONFIG_CACHE=true

## Instance
#INSTANCE_DESCRIPTION=
INSTANCE_PUBLIC_HASHTAGS=true
#INSTANCE_CONTACT_EMAIL=
INSTANCE_PUBLIC_LOCAL_TIMELINE=true
#BANNED_USERNAMES=
STORIES_ENABLED=false
RESTRICTED_INSTANCE=false
CUSTOM_EMOJI=true

## Mail
MAIL_DRIVER=smtp
MAIL_HOST=
MAIL_PORT=587
MAIL_FROM_ADDRESS="no-reply@draconis.me"
MAIL_FROM_NAME="Pixelfed"
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=tls

## Databases (MySQL)
DB_CONNECTION=mysql
DB_DATABASE=pixelfed_prod
DB_HOST=pixelfed-db
DB_PASSWORD=
DB_PORT=3306
DB_USERNAME=
# pass the same values to the db itself
MYSQL_DATABASE=pixelfed_prod
MYSQL_PASSWORD=
#MYSQL_RANDOM_ROOT_PASSWORD=true
MYSQL_ROOT_PASSWORD=
MYSQL_USER=

## Databases (Postgres)
#DB_CONNECTION=pgsql
#DB_HOST=postgres
#DB_PORT=5432
#DB_DATABASE=pixelfed
#DB_USERNAME=
#DB_PASSWORD=
#POSTGRES_PASSWORD=

## Cache (Redis)
REDIS_CLIENT=phpredis
REDIS_SCHEME=tcp
REDIS_HOST=pixelfed-redis
REDIS_PASSWORD=
REDIS_PORT=6379
REDIS_DATABASE=0

## EXPERIMENTS 
EXP_LC=false
EXP_REC=false
EXP_LOOPS=false

## ActivityPub Federation
ACTIVITY_PUB=true
AP_REMOTE_FOLLOW=true
AP_SHARED_INBOX=true
AP_INBOX=true
AP_OUTBOX=true
ATOM_FEEDS=true
NODEINFO=true
WEBFINGER=true

## S3
FILESYSTEM_DRIVER=local
FILESYSTEM_CLOUD=s3
PF_ENABLE_CLOUD=false
#AWS_ACCESS_KEY_ID=
#AWS_SECRET_ACCESS_KEY=
#AWS_DEFAULT_REGION=
#AWS_BUCKET=
#AWS_URL=
#AWS_ENDPOINT=
#AWS_USE_PATH_STYLE_ENDPOINT=false

## Horizon
HORIZON_DARKMODE=false
HORIZON_PREFIX="horizon-"

## COSTAR - Confirm Object Sentiment Transform and Reduce
PF_COSTAR_ENABLED=false

# Media
MEDIA_EXIF_DATABASE=false

## Logging
LOG_CHANNEL=stderr

## Image
IMAGE_DRIVER=imagick

## Broadcasting
BROADCAST_DRIVER=log  # log driver for local development

## Cache
CACHE_DRIVER=redis

## Purify
RESTRICT_HTML_TYPES=true

## Queue
QUEUE_DRIVER=redis

## Session
SESSION_DRIVER=redis

## Trusted Proxy
TRUST_PROXIES="*"

## Passport
#PASSPORT_PRIVATE_KEY=
#PASSPORT_PUBLIC_KEY=
````
